name: Check access
on:
  workflow_dispatch
jobs:
  check_access:
    name: access to Kuber VM
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: connect to Kuber and obtaining information about pods
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.KUBE_USER }}"@"${{ secrets.KUBE_HOST }}" \
          -o ProxyCommand="ssh -W %h:%p -q "${{secrets.JUMP_USER}}"@"${{secrets.JUMP_HOST}}"" \
          echo "status=$(kubectl get pods -A)" >> $GITHUB_ENV 
      
      - name: Status Checker
        id: check
        run: |
          echo "fc_pods=$(cat ${{env.status}} | grep -v "Running" | wc -l)" >> $GITHUB_ENV

      - name: Slack Notification good
        uses: rtCamp/action-slack-notify@v2
        if: ${{env.fc_pods}} > 0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Checking Pods
          SLACK_MESSAGE: |-
            "Everything is okay"
            "${{env.status}}"
          SLACK_TITLE: 'Checking Pods'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Report test
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.fc_pods }}