name: Check access
on:
  workflow_dispatch
jobs:
  check_access:
    name: access to Kuber VM
    runs-on: ubuntu-latest
    env:
      test: test.log
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: connect to Kuber
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts  
          ssh "${{ secrets.KUBE_USER }}"@"${{ secrets.KUBE_HOST }}" -o ProxyCommand="ssh -W %h:%p -q "${{secrets.JUMP_USER}}"@"${{secrets.JUMP_HOST}}"" \
          && ip a >> ${{env.test}}
      - name: Report test
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.test }}
