name: Check access
on:
  workflow_dispatch
jobs:
  check_access:
    outputs:
      output1: ${{ steps.check.outputs.repo }}
    name: access to Kuber VM
    runs-on: ubuntu-latest
    env:
      pods: pods.txt
      fc_pods: fc_pods.txt
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: connect to Kuber and obtaining information about pods
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.KUBE_USER }}"@"${{ secrets.KUBE_HOST }}" \
          -o ProxyCommand="ssh -W %h:%p -q "${{secrets.JUMP_USER}}"@"${{secrets.JUMP_HOST}}"" \
          kubectl get pods -A >> ${{env.pods}}
      
      - name: Status Checker
        id: check
        run: |
          echo "(cat ${{env.pods}} | grep -v "Running" | wc -l)" >> ${{env.fc_pods}}
          echo -e "(cat ${{env.pods}})" >> $GITHUB_OUTPUT    

      - name: Slack Notification good
        uses: rtCamp/action-slack-notify@v2
        if: ${{env.fc_pods}} > 0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Checking Pods
          SLACK_MESSAGE: |-
            "Everything is okay"
            "${{env.repo}}"
          SLACK_TITLE: 'Checking Pods'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}